name: Renovate

on:
  schedule:             # Run on a schedule of 3am and 6pm every Sunday
    - cron: "0 3 * * 0"  
    - cron: "0 18 * * 0"  
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}


            # Optionally, you can specify additional configuration options here
            # For example, to specify a custom config file to tell renovate where to find the file(s) 
            # instead of using the default one as the example below but since mine is at the root no need of the config-file option
            # config-file: .github/renovate.json  